// Mock data for BuildBuddy

export const MOCK_USER = {
  id: 13,
  email: "utkarsh@example.com",
  username: "Revaguest",
  full_name: "Utkarsh Aditya",
  bio: "Full-stack developer passionate about building innovative solutions",
  location: "Mumbai, India",
  skills: ["React", "TypeScript", "Python", "Django", "Node.js"],
  experience: "3 years",
  availability: "available" as const,
  role: "Full Stack Developer",
  github_url: "https://github.com/utkarsh",
  linkedin_url: "https://linkedin.com/in/utkarsh",
  portfolio_url: "https://utkarsh.dev",
};

export const MOCK_TEAMS = [
  {
    id: 14,
    name: "Shashank",
    description: "Building an AI-powered study assistant",
    category: "AI/ML",
    hackathon_name: "TechCrunch Disrupt 2024",
    lead_name: "Utkarsh Aditya",
    status: "active",
    required_skills: ["Python", "Machine Learning", "React"],
    open_positions: 2,
    member_count: 2,
    created_at: "2025-12-01T10:00:00Z",
    team_size: 4,
    current_size: 2,
    leader_id: 13,
    leader_name: "Utkarsh Aditya",
    members: [
      {
        id: 13,
        username: "Revaguest",
        full_name: "Utkarsh Aditya",
        role: "leader",
        status: "accepted",
        skills: "React, TypeScript, Python",
      },
      {
        id: 5,
        username: "sarahchen",
        full_name: "Sarah Chen",
        role: "member",
        status: "accepted",
        skills: "Python, Machine Learning",
      },
    ],
    tasks: [
      {
        id: 1,
        title: "Design UI mockups",
        description: "Create wireframes and UI designs",
        status: "in_progress",
        priority: "high",
        assigned_to_id: 13 as number | null,
        assigned_to_name: "Utkarsh Aditya" as string | null,
        created_by_id: 13,
        created_by_name: "Utkarsh Aditya",
        due_date: "2025-12-15" as string | null,
        color: "#3B82F6",
        created_at: "2025-12-01T10:00:00Z",
        updated_at: "2025-12-01T10:00:00Z",
      },
      {
        id: 2,
        title: "Setup ML model",
        description: "Train and deploy the ML model",
        status: "todo",
        priority: "high",
        assigned_to_id: 5 as number | null,
        assigned_to_name: "Sarah Chen" as string | null,
        created_by_id: 13,
        created_by_name: "Utkarsh Aditya",
        due_date: "2025-12-20" as string | null,
        color: "#10B981",
        created_at: "2025-12-01T11:00:00Z",
        updated_at: "2025-12-01T11:00:00Z",
      },
    ],
  },
  {
    id: 15,
    name: "Innovation Squad",
    description: "Healthcare app for remote patient monitoring",
    category: "Healthcare",
    hackathon_name: "Healthcare Hackathon 2024",
    lead_name: "Mike Johnson",
    status: "active",
    required_skills: ["IoT", "Cloud", "Mobile Development"],
    open_positions: 2,
    member_count: 3,
    created_at: "2025-11-28T14:00:00Z",
    team_size: 5,
    current_size: 3,
    leader_id: 8,
    leader_name: "Mike Johnson",
    members: [
      {
        id: 8,
        username: "mikej",
        full_name: "Mike Johnson",
        role: "leader",
        status: "accepted",
        skills: "IoT, Cloud, Python",
      },
      {
        id: 13,
        username: "Revaguest",
        full_name: "Utkarsh Aditya",
        role: "member",
        status: "accepted",
        skills: "React, TypeScript",
      },
      {
        id: 9,
        username: "emily",
        full_name: "Emily Davis",
        role: "member",
        status: "accepted",
        skills: "Mobile Development, Flutter",
      },
    ],
    tasks: [],
  },
];

export const MOCK_HACKATHONS = [
  {
    id: 1,
    name: "TechCrunch Disrupt 2024",
    description: "The ultimate startup competition showcasing the most innovative technology companies",
    category: "Technology",
    mode: "hybrid" as const,
    start_date: "2024-12-15",
    end_date: "2024-12-17",
    location: "San Francisco, CA",
    prize: "$100,000",
    max_participants: 500,
    participant_count: 342,
    website_url: "https://techcrunch.com/disrupt",
    registration_url: "https://techcrunch.com/disrupt/register",
    status: "upcoming",
    prize_pool: "$100,000",
    max_team_size: 5,
    registration_deadline: "2024-12-10",
    organizer: "TechCrunch",
    theme: "AI & Innovation",
  },
  {
    id: 2,
    name: "Healthcare Hackathon 2024",
    description: "Build solutions to improve healthcare accessibility and patient care",
    category: "Healthcare",
    mode: "in-person" as const,
    start_date: "2025-01-20",
    end_date: "2025-01-22",
    location: "Boston, MA",
    prize: "$50,000",
    max_participants: 300,
    participant_count: 198,
    website_url: "https://healthhack.io",
    registration_url: "https://healthhack.io/register",
    status: "upcoming",
    prize_pool: "$50,000",
    max_team_size: 4,
    registration_deadline: "2025-01-15",
    organizer: "HealthTech Alliance",
    theme: "Digital Health",
  },
  {
    id: 3,
    name: "Sustainability Challenge",
    description: "Create tech solutions for environmental sustainability and climate action",
    category: "Environment",
    mode: "remote" as const,
    start_date: "2025-02-10",
    end_date: "2025-02-12",
    location: "Seattle, WA",
    prize: "$75,000",
    max_participants: 400,
    participant_count: 267,
    website_url: "https://sustainhack.org",
    registration_url: "https://sustainhack.org/register",
    status: "upcoming",
    prize_pool: "$75,000",
    max_team_size: 6,
    registration_deadline: "2025-02-05",
    organizer: "GreenTech Initiative",
    theme: "Climate Tech",
  },
];

export const MOCK_USERS = [
  {
    id: 5,
    username: "sarahchen",
    full_name: "Sarah Chen",
    email: "sarah@example.com",
    bio: "ML engineer passionate about AI applications",
    location: "San Francisco, CA",
    skills: ["Python", "TensorFlow", "PyTorch", "Data Science"],
    experience: "5 years",
    availability: "available" as const,
    role: "ML Engineer",
    github_url: "https://github.com/sarahchen",
    linkedin_url: "https://linkedin.com/in/sarahchen",
    portfolio_url: "https://sarahchen.dev",
  },
  {
    id: 8,
    username: "mikej",
    full_name: "Mike Johnson",
    email: "mike@example.com",
    bio: "IoT and cloud architect with 5+ years experience",
    location: "Austin, TX",
    skills: ["AWS", "Azure", "IoT", "Python", "Node.js"],
    experience: "6 years",
    availability: "available" as const,
    role: "Cloud Architect",
    github_url: "https://github.com/mikejohnson",
    linkedin_url: "https://linkedin.com/in/mikejohnson",
    portfolio_url: "https://mikej.dev",
  },
  {
    id: 9,
    username: "emily",
    full_name: "Emily Davis",
    email: "emily@example.com",
    bio: "Mobile developer specializing in cross-platform apps",
    location: "New York, NY",
    skills: ["Flutter", "React Native", "Dart", "Swift"],
    experience: "3 years",
    availability: "available" as const,
    role: "Mobile Developer",
    github_url: "https://github.com/emilydavis",
    linkedin_url: "https://linkedin.com/in/emilydavis",
    portfolio_url: "https://emilydavis.dev",
  },
  {
    id: 10,
    username: "alexwang",
    full_name: "Alex Wang",
    email: "alex@example.com",
    bio: "Backend engineer with expertise in microservices",
    location: "Seattle, WA",
    skills: ["Java", "Spring Boot", "Kubernetes", "Docker"],
    experience: "7 years",
    availability: "busy" as const,
    role: "Backend Engineer",
    github_url: "https://github.com/alexwang",
    linkedin_url: "https://linkedin.com/in/alexwang",
    portfolio_url: "https://alexwang.dev",
  },
  {
    id: 11,
    username: "lisamiller",
    full_name: "Lisa Miller",
    email: "lisa@example.com",
    bio: "UX/UI designer creating beautiful user experiences",
    location: "Los Angeles, CA",
    skills: ["Figma", "Adobe XD", "User Research", "Prototyping"],
    experience: "4 years",
    availability: "available" as const,
    role: "UX/UI Designer",
    github_url: "https://github.com/lisamiller",
    linkedin_url: "https://linkedin.com/in/lisamiller",
    portfolio_url: "https://lisamiller.design",
  },
];

export const MOCK_INVITES = [];

export const MOCK_JOIN_REQUESTS = [];

export const MOCK_CONVERSATIONS = [
  {
    id: 1,
    participants: [13, 5],
    participant_names: ["Utkarsh Aditya", "Sarah Chen"],
    last_message: "Sounds good! Let's do it",
    unread_count: 0,
    updated_at: "2025-12-08T15:30:00Z",
    is_group_chat: false,
    messages: [
      {
        id: 1,
        sender_id: 13,
        sender_name: "Utkarsh Aditya",
        content: "Hey Sarah, how's the ML model coming along?",
        is_read: true,
        created_at: "2025-12-08T10:00:00Z",
      },
      {
        id: 2,
        sender_id: 5,
        sender_name: "Sarah Chen",
        content: "Going well! I've trained the initial model. Should be ready for testing tomorrow.",
        is_read: true,
        created_at: "2025-12-08T10:15:00Z",
      },
      {
        id: 3,
        sender_id: 13,
        sender_name: "Utkarsh Aditya",
        content: "Great! I'll have the frontend ready by then.",
        is_read: true,
        created_at: "2025-12-08T14:30:00Z",
      },
      {
        id: 4,
        sender_id: 5,
        sender_name: "Sarah Chen",
        content: "Sounds good! Let's do it",
        is_read: true,
        created_at: "2025-12-08T15:30:00Z",
      },
    ],
  },
  {
    id: 2,
    participants: [13, 5],
    participant_names: ["Team Shashank"],
    last_message: "Team meeting at 3 PM tomorrow",
    unread_count: 2,
    updated_at: "2025-12-08T16:00:00Z",
    is_group_chat: true,
    team_id: 14,
    team_name: "Shashank",
    messages: [
      {
        id: 5,
        sender_id: 13,
        sender_name: "Utkarsh Aditya",
        content: "Hey team! Ready for tomorrow's demo?",
        is_read: true,
        created_at: "2025-12-08T12:00:00Z",
      },
      {
        id: 6,
        sender_id: 5,
        sender_name: "Sarah Chen",
        content: "Yes! The ML part is ready. Just need to integrate with the UI.",
        is_read: false,
        created_at: "2025-12-08T14:00:00Z",
      },
      {
        id: 7,
        sender_id: 13,
        sender_name: "Utkarsh Aditya",
        content: "Perfect! Team meeting at 3 PM tomorrow to finalize everything.",
        is_read: false,
        created_at: "2025-12-08T16:00:00Z",
      },
    ],
  },
];
