# Generated by Django 5.0.1 on 2025-11-23 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('ai_ml', 'AI/ML'), ('web3', 'Web3'), ('healthtech', 'HealthTech'), ('cloud', 'Cloud'), ('spacetech', 'Space Tech'), ('fintech', 'FinTech'), ('edtech', 'EdTech'), ('other', 'Other')], max_length=20)),
                ('mode', models.CharField(choices=[('in-person', 'In-person'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('registration_open', 'Registration Open'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('prize', models.CharField(blank=True, max_length=255)),
                ('max_participants', models.IntegerField(default=500)),
                ('website_url', models.URLField(blank=True)),
                ('registration_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='HackathonRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='hackathons.hackathon')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
