# Generated by Django 5.0.1 on 2025-11-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_initial'),
        ('teams', '0006_teammembership_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='team',
            field=models.ForeignKey(blank=True, help_text='If set, this is a team group chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='teams.team'),
        ),
    ]
