# Generated by Django 5.0.1 on 2025-11-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_teamtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamtask',
            name='color',
            field=models.CharField(blank=True, default='#3B82F6', max_length=7),
        ),
    ]
