# Generated by Django 5.0.1 on 2025-11-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_teamtask_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
